name: "Deploy WebApi"

on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
        - env:
            TARGET_ENV: ${{ inputs.environment }}
          run: echo "DEPLOYING THE API to $env:TARGET_ENV..."